language: java

#needed for jdk 7
sudo: required
dist: precise

jdk:
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9

install: true

# configure caching (https://docs.travis-ci.com/user/languages/java/#Caching)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
# format from https://docs.travis-ci.com/user/caching/#Enabling-multiple-caching-features
cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
